// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBwX57XTqadYBXHavq5chyQ03dXfTJRmWc',
    appId: '1:914680086880:web:4d8e42639d6ce478709e05',
    messagingSenderId: '914680086880',
    projectId: 'todolist-flutter-saeb',
    authDomain: 'todolist-flutter-saeb.firebaseapp.com',
    storageBucket: 'todolist-flutter-saeb.firebasestorage.app',
    measurementId: 'G-6X304ZRMLV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBFEhz1h_2dz5iStfFcT2pX5VDnWjX7ylE',
    appId: '1:914680086880:android:08c0d4d587cf0b49709e05',
    messagingSenderId: '914680086880',
    projectId: 'todolist-flutter-saeb',
    storageBucket: 'todolist-flutter-saeb.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAw38UZMZGornqQqy-mwZXkBVzxiIQeAzg',
    appId: '1:914680086880:ios:e4b23ba7851bcbd4709e05',
    messagingSenderId: '914680086880',
    projectId: 'todolist-flutter-saeb',
    storageBucket: 'todolist-flutter-saeb.firebasestorage.app',
    iosBundleId: 'com.example.todoApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAw38UZMZGornqQqy-mwZXkBVzxiIQeAzg',
    appId: '1:914680086880:ios:e4b23ba7851bcbd4709e05',
    messagingSenderId: '914680086880',
    projectId: 'todolist-flutter-saeb',
    storageBucket: 'todolist-flutter-saeb.firebasestorage.app',
    iosBundleId: 'com.example.todoApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBwX57XTqadYBXHavq5chyQ03dXfTJRmWc',
    appId: '1:914680086880:web:0f55f4a561f9dcb7709e05',
    messagingSenderId: '914680086880',
    projectId: 'todolist-flutter-saeb',
    authDomain: 'todolist-flutter-saeb.firebaseapp.com',
    storageBucket: 'todolist-flutter-saeb.firebasestorage.app',
    measurementId: 'G-R5SPKM0SZ5',
  );
}
